### ISSUE TITLE
経過時間

### ISSUE THREAD

**Issue by yutokyokutyo** [yutokyokutyo/rebuild_sample_app#1]
#### 2017/03/27(月) 2h

4.1.2 カスタムヘルパー
4.2 文字列とメソッド
4.2.1 コメント
4.2.2 文字列
4.2.3 オブジェクトとメッセージ受け渡し
4.2.4 メソッドの定義
4.2.5 titleヘルパー、再び
4.3 他のデータ構造
4.3.1 配列と範囲演算子

**Comment by yutokyokutyo** [comment]
#### 20170/3/28(火)  2h

4.3.2 ブロック
4.3.3 ハッシュとシンボル

#### 感想
RubyというかLL言語の基本ができていない。
書こうと思っても書けないのは書く訓練が足りていないから。
英語、ピアノ、料理と一緒。実践の訓練が足りていないのだ〜！

**Comment by yutokyokutyo** [comment]
#### 2017/03/29(水) 2h

第5章レイアウトを作成する
5.1 構造を追加する
5.1.1 ナビゲーション
5.1.2 BootstrapとカスタムCSS
5.1.3 パーシャル (partial)
5.2 Sassとアセットパイプライン
5.2.1 アセットパイプライン
5.2.2 素晴らしい構文を備えたスタイルシート

#### 感想
- 一つづつ既存の知識が紐付いていく感じ。体系的に学ぶ恩恵を得ている。
- yutokyokutyo.org もスタイルを当てていこう。

**Comment by yutokyokutyo** [comment]
#### 2017/03/30(木) 2h

```
5.3 レイアウトのリンク
5.3.1 Contactページ
5.3.2 RailsのルートURL
5.3.3 名前付きルート
5.3.4 リンクのテスト
5.4 ユーザー登録: 最初のステップ
5.4.1 Usersコントローラ
5.4.2 ユーザー登録用URL
5.5 最後に
5.5.1 本章のまとめ
```

#### 感想
- ルーティングの部分の理解がまだ十分でないように感じた。帰ったら復習。
- 相変わらずtestが通っていないのなんとかせねば。明日聞こう。
- ちょっと集中力が切れた時間があった。もっと早く終わらせられたはずなのでふりかえってActionをだす。
- 午前中よりも16時から18時の方が良かったりするのかな。

**Comment by yutokyokutyo** [comment]
https://rebuildsampleapp.herokuapp.com/

**Comment by yutokyokutyo** [comment]
### 2017/03/31(金) 2h

```
第6章ユーザーのモデルを作成する
6.1 Userモデル
6.1.1 データベースの移行
6.1.2 modelファイル
6.1.3 ユーザーオブジェクトを作成する
6.1.4 ユーザーオブジェクトを検索する
6.1.5 ユーザーオブジェクトを更新する
6.2 ユーザーを検証する
6.2.1 有効性を検証する
6.2.2 存在性を検証する
```

### 感想
- テストが落ちている点については pry をいれて binding_pry すると良さそう！
- 演習についてはPRで管理すると他の人からもサポートをもらいやすいし、経過時間を明示しなくてもよくなって良さそう！

**Comment by june29** [comment]
`binding.pry` はハチャメチャに便利なので、ぜひご活用ください :relaxed:

> 演習についてはPRで管理すると他の人からもサポートをもらいやすい

ぼくが Issue で「テストが通らない〜」というのを見かけたとき、どの時点のコードで実行したテストなのだろう？というのがすぐにはわからなかったのでした。Pull Request なら、少なくとも「このブランチの話だな〜」とわかるので、よさそうと思った次第です :bulb:

**Comment by yutokyokutyo** [comment]
#### 2017/04/4(火) 2h
```
今までの復習
7.3.4 失敗時のテスト
```

復習はできたけど、失敗時のテスト `assert_select`  の使い方を調べるのに１時間位使ってしまった..。

**Comment by kurotaky** [comment]
@yutokyokutyo 
時間がかかってしまうのはしょうがないです。
結果として理解できたならそれは素晴らしいことです！

最初は時間がかかってしまうかもしれないですが、
`問題の認識 → 問題解決のための計画を立てる → 実行する → 結果を確認する・ふりかえる`
を繰り返して、問題解決筋肉を鍛えていきましょう！
細かいことはまた明日確認しましょう〜

**Comment by yutokyokutyo** [comment]
## スケジュール見直し
### 目標
4/21, 4/25 くらいにはTutorialを終わらせたい。

### マイルストーン

- 4/9 : 9章完
- 4/14: 11章半分完
- 4/16: 12章完
- 4/20: 13章完
- 4/25: 14章完

**Comment by yutokyokutyo** [comment]
5/16(火) 完！
